config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'slots#index'
  resources :slots do
    get 'view', on: :collection
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :slots
  default_scope {order('name ASC')}
end

app/models/room.rb
class Room < ActiveRecord::Base
  has_many :slots
end

app/models/slot.rb
class Slot < ActiveRecord::Base
  belongs_to :group
  belongs_to :room
  validate :group_ineligible_for_assignment, :cant_reassign_group
  validates :start_time, :end_time, presence: true
  default_scope -> {order("start_time ASC")}
  
  def group_ineligible_for_assignment
    unless group.nil? or not changes.include?("group_id")
      if group.slots.where("start_time > ?", Time.now).count > 0
        errors.add(:group, "already assigned to upcoming slot")
      end
    end
  end

  def cant_reassign_group
    unless group_id_was.nil? or not changes.include?("group_id")
      errors.add(:group, "can't reassign assigned slot")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/slots_controller.rb
class SlotsController < ApplicationController
  respond_to :html
  def index
    params["room_id"] ||= '1'
    @rooms = Room.all
    @room = Room.find(params["room_id"])
    respond_with @room
  end

  def view
    @rooms = Room.all
    respond_with @rooms
  end

  def update
    @slot = Slot.find(params[:id])
    begin
      @slot.update_attributes!(permitted_params)
    rescue ActiveRecord::RecordInvalid
      flash[:error] = @slot.errors.full_messages
    end
    redirect_to root_path
  end

  private
    def permitted_params
      params.require(:slot).permit(:id, :group_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "SDP Pitch Schedule" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="row">
      <div class="small-12 columns">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/slots/index.html.erb
<% if flash[:error] %>
  <div id="error_explanation" class="panel">
    <h2><%= pluralize(flash[:error].count, "error") %> prohibited this assignment from being saved:</h2>

    <ul>
    <% flash[:error].each do |atr, msg| %>
      <li><%= atr %> <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<h1>SDP Pitch Booking</h1>
<ul>
  <li>Each group can hold one booking at a time</li>
  <li>You must wait until your booking has started in order to make another booking</li>
</ul>

<dl class="sub-nav">
  <dt>Room:</dt>
  <% @rooms.each do |r| %>
    <dd><%= link_to r.name, slots_path(room_id: r) %></dd>
  <% end %>
</dl>

<h2><%= @room.name %></h2>
<div class="small-12 columns">
<table>
  <thead>
    <tr>
      <th width="250">Time</th>
      <th width="500">Group</th>
    </tr>
  </thead>
  <tbody>
    <% @room.slots.each do |slot| %>
        <tr>
          <td>
            <%= slot.start_time.to_formatted_s(:long) %> - <%= slot.end_time.to_formatted_s(:time) %>
          </td>
          <td>
            <%= form_for(slot, url: slot_path(slot.id)) do |f| %>
              <%= if slot.end_time > Time.now
                f.collection_select :group_id, Group.all, :id, :name, include_blank: " "
              else
                slot.group.name unless slot.group.nil?
              end %>
            <% end %>
          </td>
        </tr>
    <% end %>
  </tbody>
</table>
</div>
<script>
  $("select").change(function() {
    $(this).parents("form").submit();
  });
</script>

app/views/slots/view.html.erb
<h1>SDP Pitch Booking</h1>
<div class="row">
  <% @rooms.each do |room| %>
  <div class="large-6 columns">
    <h2><%= room.name %></h2>
    <div class="small-12 columns">
    <table>
      <thead>
        <tr>
          <th width="250">Time</th>
          <th width="500">Group</th>
        </tr>
      </thead>
      <tbody>
        <% room.slots.where("end_time >= ?", Time.now).limit(10).each do |slot| %>
            <tr>
              <td>
                <%= slot.start_time.to_formatted_s(:long) %> - <%= slot.end_time.to_formatted_s(:time) %>
              </td>
              <td>
                <%= slot.group.name unless slot.group.nil? %>
              </td>
            </tr>
        <% end %>
      </tbody>
    </table>
    </div>
  </div>
  <% end %>
</div>
<script>
  setInterval(function() {location.reload(true); }, 60 * 1000);
</script>